packer {
  required_plugins {
    amazon = {
      version = ">= 1.2.8"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
  description = "The AWS region to build the AMI in."
}

variable "ami_name_prefix" {
  type    = string
  default = "centos-9"
}

variable "build_id" {
  type        = string
  description = "The unique identifier for this build, typically the CI/CD run ID."
}

variable "platform" {
  type        = string
  description = "The target platform (aws, gcp, azure)."
}

source "amazon-ebs" "autogenerated" {
  region          = var.aws_region
  instance_type   = "t2.micro"
  ssh_username    = "centos"
  
  source_ami_filter {
    filters = {
      name                = "CentOS-Stream-9-*-x86_64-*"
      root-device-type    = "ebs"
      virtualization-type = "hvm"
    }
    most_recent = true
    owners      = ["125523088429"]
  }

  ami_name = "${var.ami_name_prefix}-${var.platform}-${var.build_id}"
  tags = {
    Name        = "PremierManagedOS Image"
    OS_Version  = "centos-9"
    Base_AMI_ID = "{{ .SourceAMI }}"
    Created_By  = "Packer"
  }
}

build {
  name    = "build-centos-9-aws"
  sources = ["source.amazon-ebs.autogenerated"]

  provisioner "shell" {
    inline = [
      "echo 'Waiting for cloud-init to finish...'",
      "cloud-init status --wait || echo 'cloud-init not found, continuing...'",
      "echo 'Updating packages...'",
      "if [ -f /usr/bin/apt-get ]; then sudo apt-get clean; for i in {1..3}; do sudo apt-get update -y && break || sleep 15; done; sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y; fi",
      "if [ -f /usr/bin/yum ]; then sudo yum -y update; fi",
      "if [ -f /usr/bin/dnf ]; then sudo dnf -y update; fi"
    ]
  }

  provisioner "shell" {
    inline = [
      "echo 'Installing common tools...'",
      "if [ -f /usr/bin/apt-get ]; then sudo apt-get install -y curl wget unzip; fi",
      "if [ -f /usr/bin/yum ]; then sudo yum install -y curl wget unzip; fi",
      "if [ -f /usr/bin/dnf ]; then sudo dnf install -y curl wget unzip; fi"
    ]
  }
}