packer {
  required_plugins {
    googlecompute = {
      version = ">= 1.1.2"
      source  = "github.com/hashicorp/googlecompute"
    }
  }
}

variable "gcp_project_id" {
  type = string
  description = "GCP project ID for the build."
}
variable "gcp_zone" {
  type    = string
  default = "us-central1-a"
}

variable "build_id" {
  type        = string
  description = "The unique identifier for this build, typically the CI/CD run ID."
}

variable "platform" {
  type        = string
  description = "The target platform (aws, gcp, azure)."
}

source "googlecompute" "autogenerated" {
  project_id          = var.gcp_project_id
  zone                = var.gcp_zone
  source_image_family = "fedora-cloud-38"
  source_image_project_id = ["fedora-cloud"]
  ssh_username        = "packer"
  machine_type        = "e2-medium"
  image_name          = "fedora-38-${var.platform}-${var.build_id}"
  image_family        = "fedora-38"

  tags = ["packer-build"]
}

build {
  name    = "build-fedora-38-gcp"
  sources = ["source.googlecompute.autogenerated"]

  provisioner "shell" {
    inline = [
      "echo 'Updating packages...'",
      "if [ -f /usr/bin/apt-get ]; then sudo apt-get update && sudo apt-get -y upgrade; fi",
      "if [ -f /usr/bin/yum ]; then sudo yum -y update; fi",
      "if [ -f /usr/bin/dnf ]; then sudo dnf -y update; fi"
    ]
  }
}