packer {
  required_plugins {
    googlecompute = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/googlecompute"
    }
  }
}

variable "gcp_project_id" {
  type    = string
}

variable "build_id" {
  type    = string
  default = "local"
}

source "googlecompute" "autogenerated" {
  project_id          = var.gcp_project_id
  source_image_family = "ubuntu-2204-lts"
  source_image_project_id = "ubuntu-os-cloud"
  zone                = "us-central1-a"
  instance_name       = "packer-ubuntu-20-04-${var.build_id}"
  image_name          = "ubuntu-20-04-${var.build_id}"
  ssh_username        = "packer"
  
  
  
  

  metadata = {
    "created-by" = "Packer"
  }
}

build {
  sources = ["source.googlecompute.autogenerated"]
}