packer {
  required_plugins {
    azure = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/azure"
    }
  }
}



variable "build_id" {
  type    = string
  default = "local"
}

variable "platform" {
  type    = string
  default = "unknown"
}

source "azure-arm" "autogenerated" {
  use_azure_cli_auth = true
  image_offer     = "0001-com-ubuntu-server-focal"
  image_publisher = "canonical"
  image_sku       = "20_04-lts-gen2"
  os_type         = "Linux"
  
  managed_image_name                       = "ubuntu-20-04-${var.build_id}"
  managed_image_resource_group_name        = "rg-packer-images"
  
  vm_size         = "Standard_DS2_v2"
  
  
  
}

build {
  sources = ["source.azure-arm.autogenerated"]
}