packer {
  required_plugins {
    azure = {
      version = ">= 2.0.0"
      source  = "github.com/hashicorp/azure"
    }
  }
}



variable "resource_group_name" {
  type    = string
  default = "rg-packer-images"
}
variable "location" {
  type    = string
  default = "East US"
}

variable "build_id" {
  type        = string
  description = "The unique identifier for this build, typically the CI/CD run ID."
}

variable "platform" {
  type        = string
  description = "The target platform (aws, gcp, azure)."
}

source "azure-arm" "autogenerated" {
  use_oidc          = true

  managed_image_resource_group_name = var.resource_group_name
  managed_image_name                = "ubuntu-20.04-${var.platform}-${var.build_id}"
  
  location          = var.location
  vm_size           = "Standard_D2s_v3"
  
  image_publisher   = "Canonical"
  image_offer       = "0001-com-ubuntu-server-focal"
  image_sku         = "20_04-lts-gen2"
  image_version     = "latest"

  os_type           = "Linux"
}

build {
  name    = "build-ubuntu-20.04-azure"
  sources = ["source.azure-arm.autogenerated"]

  provisioner "shell" {
    inline = [
      "echo 'Waiting for cloud-init to finish...'",
      "cloud-init status --wait || echo 'cloud-init not found, continuing...'",
      "echo 'Updating packages...'",
      "if [ -f /usr/bin/apt-get ]; then sudo apt-get clean; for i in {1..3}; do sudo apt-get update -y && break || sleep 15; done; sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y; fi",
      "if [ -f /usr/bin/yum ]; then sudo yum -y update; fi",
      "if [ -f /usr/bin/dnf ]; then sudo dnf -y update; fi"
    ]
  }
}