packer {
  required_plugins {
    amazon = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

variable "build_id" {
  type    = string
  default = "local"
}

source "amazon-ebs" "autogenerated" {
  ami_name      = "ubuntu-20-04-${var.build_id}"
  instance_type = "t3.medium"
  region        = "us-east-1"
  source_ami_filter {
    filter {
      name                = "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
      owners              = ["099720109477"] # Canonical's owner ID
      virtualization-type = "hvm"
    }
    most_recent = true
  }
  ssh_username  = "ubuntu"
  
  
  

  tags = {
    Name      = "ubuntu-20.04"
    OS_Version = "ubuntu-20.04"
    CreatedBy = "Packer"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated"]
}