packer {
  required_plugins {
    amazon = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

variable "build_id" {
  type    = string
  default = "local"
}

variable "platform" {
  type    = string
  default = "unknown"
}

variable "vm_size" {
  type    = string
  default = "t3.medium"
}

variable "region" {
  type    = string
}

source "amazon-ebs" "autogenerated" {
  ami_name      = "ubuntu-24-04-${var.platform}-${var.build_id}"
  instance_type = var.vm_size
  region        = var.region
  
  source_ami_filter {
    filters = {
      name                = "ubuntu/images/hvm-ssd/ubuntu-noble-24.04-amd64-server-*"
      virtualization-type = "hvm"
    }
    owners      = ["099720109477"]
    most_recent = true
  }
  ssh_username  = "ubuntu"
  
  
  
  

  tags = {
    Name      = "ubuntu-24.04"
    OS_Version = "ubuntu-24.04"
    CreatedBy = "Packer"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated"]
}