name: Delete Packer Image

on:
  repository_dispatch:
    types: [delete-image]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: 'Debug: Show Webhook Payload'
        run: |
          echo "Deleting image: ${{ github.event.client_payload.image_name }}"
          echo "Platform: ${{ github.event.client_payload.platform }}"

      # --- GCP Deletion ---
      - name: Authenticate to Google Cloud
        if: github.event.client_payload.platform == 'gcp'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - name: Delete GCP Image
        if: github.event.client_payload.platform == 'gcp'
        run: |
          gcloud compute images delete ${{ github.event.client_payload.image_name }} --project=${{ github.event.client_payload.project_id }} --quiet

      # --- AWS Deletion ---
      - name: Configure AWS Credentials
        if: github.event.client_payload.platform == 'aws'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.client_payload.region || 'us-east-1' }}

      - name: Delete AWS AMI
        if: github.event.client_payload.platform == 'aws'
        run: |
          # The image_name payload should be the AMI ID
          aws ec2 deregister-image --image-id ${{ github.event.client_payload.image_name }}
          # Note: This does not delete the underlying snapshot. Manual snapshot cleanup might be needed for cost savings.

      # --- Azure Deletion ---
      - name: Azure Login
        if: github.event.client_payload.platform == 'azure'
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Delete Azure Image
        if: github.event.client_payload.platform == 'azure'
        run: |
          az image delete --resource-group ${{ github.event.client_payload.resource_group }} --name ${{ github.event.client_payload.image_name }} --yes
