# Configure the AzureRM Provider
# Ensures features are enabled and skips provider registration to prevent permission errors.
provider "azurerm" {
  features {}
  skip_provider_registration = true
}

# --- Variables for Configuration ---
# These variables define configurable aspects of the virtual machine deployment.
variable "instance_name" {
  description = "The name of the virtual machine instance."
  type        = string
  default     = "test-neil-21" # From JSON: platform.instanceName
}

variable "vm_size" {
  description = "The size of the virtual machine (e.g., Standard_B1s, Standard_DS1_v2)."
  type        = string
  default     = "Standard_B1s" # From JSON: platform.vmSize
}

variable "custom_image_name" {
  description = "The name of the custom image to use for the VM."
  type        = string
  default     = "ubuntu-20-04-19123432891" # From CRITICAL INSTRUCTIONS
}

variable "azure_resource_group_name" {
  description = "The name of the existing Azure Resource Group where resources will be deployed."
  type        = string
  default     = "umos" # From JSON: azure_resource_group
}

# --- Data Source for Existing Azure Resource Group ---
# Looks up the existing Azure Resource Group based on the provided name.
# This resource group is assumed to exist and is NOT created by this script.
data "azurerm_resource_group" "rg" {
  name = var.azure_resource_group_name
}

# --- SSH Key Generation for Linux VM ---
# Generates a new RSA private key locally. The public key will be used for SSH access to the VM.
# CRITICAL: This is used for the admin_ssh_key block in the VM resource.
resource "tls_private_key" "admin_ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# --- Networking Resources ---

# Virtual Network (VNet)
# Defines a new virtual network within the existing resource group's location.
resource "azurerm_virtual_network" "vnet" {
  name                = "${var.instance_name}-vnet"
  address_space       = ["10.0.0.0/16"]
  location            = data.azurerm_resource_group.rg.location
  resource_group_name = data.azurerm_resource_group.rg.name
}

# Subnet
# Defines a subnet within the created virtual network.
resource "azurerm_subnet" "subnet" {
  name                 = "${var.instance_name}-subnet"
  resource_group_name  = data.azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.0.1.0/24"]
}

# Network Interface (NIC)
# Creates a network interface for the virtual machine with a dynamic private IP.
resource "azurerm_network_interface" "nic" {
  name                = "${var.instance_name}-nic"
  location            = data.azurerm_resource_group.rg.location
  resource_group_name = data.azurerm_resource_group.rg.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.subnet.id
    private_ip_address_allocation = "Dynamic"
  }
}

# --- Primary Compute Resource: Azure Linux Virtual Machine ---
# Deploys a Linux virtual machine using the specified custom image.
# CRITICAL: Named "this_vm" as per instructions.
resource "azurerm_linux_virtual_machine" "this_vm" {
  name                = var.instance_name
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = data.azurerm_resource_group.rg.location
  size                = var.vm_size
  admin_username      = "azureuser" # Common default for Linux VMs
  network_interface_ids = [
    azurerm_network_interface.nic.id,
  ]

  # Configuration for the OS disk
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
    disk_size_gb         = 30 # Default OS disk size, can be adjusted.
  }

  # Specifies the custom image to use for the VM.
  # The source_image_id is constructed based on the existing resource group's ID
  # and the provided custom image name. This assumes a managed image.
  source_image_id = "${data.azurerm_resource_group.rg.id}/providers/Microsoft.Compute/images/${var.custom_image_name}"

  # SSH Public Key for Admin Access
  # Uses the public key generated by the tls_private_key resource.
  # CRITICAL: `public_key_openssh` is used as specified.
  admin_ssh_key {
    username   = "azureuser"
    public_key = tls_private_key.admin_ssh.public_key_openssh
  }

  # Disables password authentication for enhanced security.
  disable_password_authentication = true
}

# --- Outputs ---

# Output the private IP address of the virtual machine.
# CRITICAL: Named "private_ip" and references the correct attribute.
output "private_ip" {
  description = "The private IP address of the created virtual machine."
  value       = azurerm_linux_virtual_machine.this_vm.private_ip_address
}